#ifndef CONTAR_OCURRENCIAS_SOLAPAMIENTO_H_INCLUDED
#define CONTAR_OCURRENCIAS_SOLAPAMIENTO_H_INCLUDED

int contar_ocurrencias_solapamiento(char* , char* );

#endif // CONTAR_OCURRENCIAS_SOLAPAMIENTO_H_INCLUDED
